Models/ErrorViewModel.cs
namespace CRUDPROJECT.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TBLPRODUCTOSModel.cs
using System.ComponentModel.DataAnnotations;    

namespace CRUDPROJECT.Models
{
    public class TBLPRODUCTOSModel
    {

        public int IdProducto  { get; set; }

        [Required(ErrorMessage = "El campo Nombre es obligatorio")]
        public string NombreProd { get; set; }
        [Required(ErrorMessage = "El campo Precio es obligatorio")]
        public int Precio { get; set; }
        [Required(ErrorMessage = "El campo Descripcion es obligatorio")]
        public string DescripcionProd { get; set; }
    
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CRUDPROJECT.Models;

namespace CRUDPROJECT.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;

using CRUDPROJECT.Datos;
using CRUDPROJECT.Models;

namespace CRUDPROJECT.Controllers
{
    public class MantenedorController : Controller
    {
        TBLProductosDatos _ProductosDatos = new TBLProductosDatos();
        public IActionResult Listar()
        {
            var oLista = _ProductosDatos.Listar();

            return View(oLista);
        }

        public IActionResult Guardar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(TBLPRODUCTOSModel oProducto)
        {
            if(!ModelState.IsValid)
                return View();

            var respuesta = _ProductosDatos.Guardar(oProducto);

            if(respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Editar(int IdProducto)
        {
            var oProducto = _ProductosDatos.Obtener(IdProducto);
            return View(oProducto);
        }

        [HttpPost]
        public IActionResult Editar(TBLPRODUCTOSModel oProducto)
        {
            if (!ModelState.IsValid)
                return View();

            var respuesta = _ProductosDatos.Editar(oProducto);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int IdProducto)
        {
            var oProducto = _ProductosDatos.Obtener(IdProducto);
            return View(oProducto);
        }

        [HttpPost]
        public IActionResult Eliminar(TBLPRODUCTOSModel oProducto)
        {
            
            var respuesta = _ProductosDatos.Eliminar(oProducto.IdProducto);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }


    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Mantenedor/Editar.cshtml
@model TBLPRODUCTOSModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Editar Producto
    </div>
    <div class="card-body">
        <form asp-action="Editar" asp-controller="Mantenedor" method="post">

            <input asp-for="IdProducto" type="hidden" class="form-control">
            <div class="mb-3">
                <label class="form-label">Nombre Producto</label>
                <input asp-for="NombreProd" type="text" class="form-control">
                <span asp-validation-for="NombreProd" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Precio</label>
                <input asp-for="Precio" type="text" class="form-control">
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Descripcion</label>
                <input asp-for="DescripcionProd" type="text" class="form-control">
                <span asp-validation-for="DescripcionProd" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

Views/Mantenedor/Eliminar.cshtml
@model TBLPRODUCTOSModel
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Editar Producto
    </div>
    <div class="card-body">
        <form asp-action="Eliminar" asp-controller="Mantenedor" method="post">

            <input asp-for="IdProducto" type="hidden" class="form-control">
           
            <div class="alert alert-danger" role="alert">
                Desea eliminar el producto? : @Html.DisplayTextFor(mbox => mbox.NombreProd) ?
            </div>

            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

Views/Mantenedor/Guardar.cshtml
@model TBLPRODUCTOSModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Producto
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Mantenedor" method="post">
            <div class="mb-3">
                <label class="form-label">Nombre Producto</label>
                <input asp-for="NombreProd" type="text" class="form-control">
                <span asp-validation-for="NombreProd" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Precio</label>
                <input asp-for="Precio" type="text" class="form-control">
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Descripcion</label>
                <input asp-for="DescripcionProd" type="text" class="form-control">
                <span asp-validation-for="DescripcionProd" class="text-danger"></span>
            </div>
            
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

Views/Mantenedor/Listar.cshtml
@model List<TBLPRODUCTOSModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Lista Productos
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-success">Crear Nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nombre Producto</th>
                    <th>Precio</th>
                    <th>Descripcion</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.NombreProd</td>
                        <td>@item.Precio</td>
                        <td>@item.DescripcionProd</td>
                        <td>
                            <a asp-action="Editar" asp-controller="Mantenedor" class="btn btn-primary btn-sm" asp-route-IdProducto="@item.IdProducto" >Editar</a>
                            <a asp-action="Eliminar" asp-controller="Mantenedor" class="btn btn-danger btn-sm" asp-route-IdProducto="@item.IdProducto" >Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDPROJECT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUDPROJECT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUDPROJECT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CRUDPROJECT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>